### ISSUE TITLE
Segmentation fault on share/fetch_curl.c

### ISSUE THREAD

**Issue by antsuke42** [Neverball/neverball#237]
The game opens a window, freezes for a second and crashes from a segmentation fault.
GDB Log:
```
Starting program: /home/anttu/neverball/neverball 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffec50a640 (LWP 33295)]
[New Thread 0x7fffebd09640 (LWP 33296)]
[New Thread 0x7fffeb508640 (LWP 33297)]
[New Thread 0x7fffead07640 (LWP 33298)]
[New Thread 0x7fffea4c5640 (LWP 33299)]
[Thread 0x7fffea4c5640 (LWP 33299) exited]
[New Thread 0x7fffea4c5640 (LWP 33300)]
[Thread 0x7fffea4c5640 (LWP 33300) exited]
[New Thread 0x7fffe9953640 (LWP 33301)]
[New Thread 0x7fffea4c5640 (LWP 33302)]
[New Thread 0x7fffe98ea640 (LWP 33303)]
[New Thread 0x7fffe9096640 (LWP 33304)]
[New Thread 0x7fffe8875640 (LWP 33305)]
[Thread 0x7fffe8875640 (LWP 33305) exited]
[New Thread 0x7fffe8875640 (LWP 33314)]
[Thread 0x7fffe98ea640 (LWP 33303) exited]

Thread 9 "fetch" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffea4c5640 (LWP 33302)]
0x00005555555c1198 in fetch_write_func (buffer=0x7fffbc0011cf, size=1, nmemb=977, user_data=0x55555591be30) at share/fetch_curl.c:299
299                 if (fi->dest_filename && *fi->dest_filename)
```

**Comment by parasti** [comment]
Hi, can you recompile with "make DEBUG=1" and post the "bt full" output from gdb, after the crash?

**Comment by antsuke42** [comment]
```
#0  0x00005555555c1198 in fetch_write_func (buffer=0x7fffbc0011cf, size=1, nmemb=979, user_data=0x55555591c570) at share/fetch_curl.c:299
        fi = 0x55555591c570
#1  0x00007ffff7f4f666 in ?? () from /usr/lib/libcurl.so.4
No symbol table info available.
#2  0x00007ffff7f627b9 in ?? () from /usr/lib/libcurl.so.4
No symbol table info available.
#3  0x00007ffff7f47605 in ?? () from /usr/lib/libcurl.so.4
No symbol table info available.
#4  0x00007ffff7f48c36 in curl_multi_perform () from /usr/lib/libcurl.so.4
No symbol table info available.
#5  0x00005555555c12d0 in fetch_step () at share/fetch_curl.c:340
        running_handles = 0
#6  0x00005555555c14f8 in fetch_thread_func (data=0x0) at share/fetch_curl.c:431
        code = CURLM_OK
#7  0x00007ffff7de58d1 in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#8  0x00007ffff7e84caa in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#9  0x00007ffff7ac0259 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#10 0x00007ffff79e95e3 in clone () from /usr/lib/libc.so.6
No symbol table info available.
```

**Comment by parasti** [comment]
That seems fine. Hmm. What system is this on?

**Comment by antsuke42** [comment]
I'm on Arch Linux, packages should be up-to-date. 
I think I'm going to try building neverball git on my Ubuntu laptop.

**Comment by antsuke42** [comment]
The release version of neverball 1.6.0 doesn't segfault and i also tried building neverball git on a year-old commit (939cfc66) and it doesn't crash either, so it might be a recent change.

**Comment by parasti** [comment]
This crash is is very new code. I recently added in-game package downloads (can be disabled with ENABLE_FETCH=null). This crash happens in the libcurl backend on first write. It seems like an impossible situation, but I must have missed something. The more details we can get on this, the better.

**Comment by ersohnstyne** [comment]
Use ENABLE_FETCH=0 to disable downloads. It is very easier to use.
